### ISSUE TITLE
Puszczanie myszki poza przyciskiem

### ISSUE THREAD

**Issue by hXR16F** [ctrl-team/niestop#1]
![ezgif-1-49ce273ff9d3](https://user-images.githubusercontent.com/48186982/71322188-1ce2bc00-24c5-11ea-8516-22f8be07f8c9.gif)

**Comment by Nimplex** [comment]
poprawimy to

**Comment by Nimplex** [comment]
naprawione. https://github.com/ctrl-team/niestop/commit/03a55c1ec17b46bc22f5da92d5bcc39308f0cb90
